spring:
  application:
    name: recipebase-server
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres